site_name: Printer Modding
site_url: printermodding.github.io
nav:
  - Home: index.md
  - Elegoo Neptune 3:
      - Types:
          - Comments: v1/types/comments.md
          - Posts: v1/types/posts.md


theme: readthedocs