site_name: Printer Modding
site_url: https://printermodding.github.io/docs
nav:
  - Home: marlin.md
  - Elegoo Neptune 3:
      - 'Firmware':
          - 'Marlin (Factory default)': elegoo/neptune3/firmware/marlin.md
      - 'Modding':
          - 'Dual Extruder': elegoo/neptune3/modding/dualextruder.md

theme:
  name: material
