site_name: Printer Modding
site_url: https://printermodding.github.io/docs
nav:
  - Home: index.md
  - Klipper: klipper.md
theme:
  name: material
  custom_dir: docs/overrides/

plugins:
  - search
  - git-committers:
      repository: printermodding/printermodding.github.io
      branch: main
      token: !!python/object/apply:os.getenv [ "MKDOCS_GIT_COMMITTERS_APIKEY" ]
  - git-revision-date-localized
  - include-markdown

markdown_extensions:
  - attr_list
  - md_in_html
extra_css:
  - main.css


